spring:
  application:
    name: ${SPRING_APP_NAME:spring-security}
  config:
    import:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3311}/${DATABASE_NAME:springsecurity}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate.format_sql: ${HIBERNATE_FORMAT_SQL:true} # Format SQL queries for better readability
  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8180/realms/spring-security-dev/protocol/openid-connect/certs}
#        opaquetoken:
#          introspection-uri: ${INTROSPECTION_URI:http://localhost:8180/realms/spring-security-dev/protocol/openid-connect/token/introspect}
#          client-id: ${INTROSPECTION_CLIENT_ID:spring-security-introspect}
#          client-secret: ${INTROSPECTION_CLIENT_SECRET:RxlMbOuLEOrhlraVpAZTR8Yh9RlCyWJu}

server:
  servlet:
    session:
      timeout: ${SERVER_SERVLET_SESSION_TIMEOUT:20m} # Session timeout duration

logging:
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
